name: Create S3 Static Site

on:
  issues:
    type:
      - opened
    
    jobs:
      deploy:
        runs-on: ubuntu-latest

      steps:
        -name: Checkout repository
        uses: actions/checkout@v2

        -name: Set Up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETS_ACCESS_KEY_ID }}
          aws-region: us-east-2

        -name: Extract Bucket Name
        run: |
          export BUCKET_NAME=$(echo" ${{ github.event.issue.title }}")
          echo "bucket Name: $BUCKET_NAME"
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

        -name: Run Terraform
        run: |
          cd terraform
          cd S3-MED-STATIC
          terraform init
          terraform apply -auto-approve -var="bucket_name=${{ env.BUCKET_NAME }}"


